### ISSUE TITLE
android.content.ActivityNotFoundException

### ISSUE THREAD

**Issue by Mbayrak25** [Elringus/UnityGoogleDrive#138]
Hi this is my android logcat logs : 
its working on editor but not workin when i take android build... 
2024.03.13 16:06:24.141 19198 19234 Debug tudio.booomzaaa PlayerBase::stop() from IPlayer
2024.03.13 16:06:24.142 19198 19234 Debug AudioTrack stop(428): called with 250800 frames delivered
2024.03.13 16:06:25.179 19198 19198 Debug AndroidRuntime Shutting down VM
0001.01.01 00:00:00.000 -1 -1 Info  --------- beginning of crash
2024.03.13 16:06:25.181 19198 19198 Error AndroidRuntime FATAL EXCEPTION: main
2024.03.13 16:06:25.181 19198 19198 Error AndroidRuntime Process: com.mbyrockstudio.booomzaaa, PID: 19198
2024.03.13 16:06:25.181 19198 19198 Error AndroidRuntime java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mbyrockstudio.booomzaaa/**com.elringus.unitygoogledriveandroid.AuthorizationActivity}: android.content.ActivityNotFoundException**
2024.03.13 16:06:25.181 19198 19198 Error AndroidRuntime 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3645)
2024.03.13 16:06:25.181 19198 19198 Error AndroidRuntime 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
2024.03.13 16:06:25.181 19198 19198 Error AndroidRuntime 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
2024.03.13 16:06:25.181 19198 19198 Error AndroidRuntime 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
2024.03.13 16:06:25.181 19198 19198 Error AndroidRuntime 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
2024.03.13 16:06:25.181 19198 19198 Error AndroidRuntime 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
2024.03.13 16:06:25.181 19198 19198 Error AndroidRuntime 	at android.os.Handler.dispatchMessage(Handler.java:106)
2024.03.13 16:06:25.181 19198 19198 Error AndroidRuntime 	at android.os.Looper.loopOnce(Looper.java:201)
2024.03.13 16:06:25.181 19198 19198 Error AndroidRuntime 	at android.os.Looper.loop(Looper.java:288)
2024.03.13 16:06:25.181 19198 19198 Error AndroidRuntime 	at android.app.ActivityThread.main(ActivityThread.java:7959)
2024.03.13 16:06:25.181 19198 19198 Error AndroidRuntime 	at java.lang.reflect.Method.invoke(Native Method)
2024.03.13 16:06:25.181 19198 19198 Error AndroidRuntime 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
2024.03.13 16:06:25.181 19198 19198 Error AndroidRuntime 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
2024.03.13 16:06:25.181 19198 19198 Error AndroidRuntime Caused by: android.content.ActivityNotFoundException
2024.03.13 16:06:25.181 19198 19198 Error AndroidRuntime 	at net.openid.appauth.AuthorizationService.prepareAuthorizationRequestIntent(AuthorizationService.java:372)
2024.03.13 16:06:25.181 19198 19198 Error AndroidRuntime 	at net.openid.appauth.AuthorizationService.getAuthorizationRequestIntent(AuthorizationService.java:267)
2024.03.13 16:06:25.181 19198 19198 Error AndroidRuntime 	at net.openid.appauth.AuthorizationService.getAuthorizationRequestIntent(AuthorizationService.java:296)
2024.03.13 16:06:25.181 19198 19198 Error AndroidRuntime 	at com.elringus.unitygoogledriveandroid.AuthorizationActivity.onCreate(AuthorizationActivity.java:50)
2024.03.13 16:06:25.181 19198 19198 Error AndroidRuntime 	at android.app.Activity.performCreate(Activity.java:8348)
2024.03.13 16:06:25.181 19198 19198 Error AndroidRuntime 	at android.app.Activity.performCreate(Activity.java:8327)
2024.03.13 16:06:25.181 19198 19198 Error AndroidRuntime 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1423)
2024.03.13 16:06:25.181 19198 19198 Error AndroidRuntime 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
2024.03.13 16:06:25.181 19198 19198 Error AndroidRuntime 	... 12 more

**Comment by Mbayrak25** [comment]
i found solution , thank you 👍 https://github.com/elringus/unity-google-drive/issues/122#issuecomment-1774168592
now i have a new problem :)
![WhatsApp Görsel 2024-03-14 saat 08 44 26_6bdce981](https://github.com/elringus/unity-google-drive/assets/104818716/c3f5ee6a-3b96-40c6-8ca0-0840f4c531a2)

**Comment by Mbayrak25** [comment]
it solved too , close the post 🙂
